language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.4
    - RACKET_VERSION=6.5
    - RACKET_VERSION=6.6
    - RACKET_VERSION=7.4 RUN_COVER=true
    - RACKET_VERSION=HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - raco pkg install --auto cover cover-coveralls doc-coverage

install:
  - raco pkg install --auto $TRAVIS_BUILD_DIR

script:
  - raco test -c request
  - raco test --submodule integration-test request
  - raco doc-coverage request
  - if [ -n "$RUN_COVER" ]; then raco cover -f coveralls -d $TRAVIS_BUILD_DIR/coverage -c request; fi
